server:
  port: 8081

spring:
  artemis:
    mode: native
    host: artemis-mq-service
    port: 61616
    user: artemis
    password: artemis
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql3221:3306/family?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2&useLegacyDatetimeCode=false
    username: user
    password: 123

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        TYPE: TRACE